### PR TITLE
fix compiler warnings

### PR DESCRIPTION
**Pull request by rwcarlsen**

### CODE REVIEW

**Comment by gonuke** [comment]
Thanks!  I must not be keeping you busy enough :)

**Comment by rwcarlsen** [comment]
Pretty easy fixes (about 30 min of work) - just did what the compiler told
me.  Should fix some pretty serious memory leak issues among other things.
But fixes like this probably just make it even less likely ALARA ever gets
its long overdue rewrite :-)

**Comment by elliottbiondo** [comment]
These fixes don't seem to break anything on a full-scale problem.

**Comment by gonuke** [comment]
And the closest thing we have to tests are the sample problems, for which we diff the outputs.

It passes there - I'll merge.

**Pull request merged**
