### PR TITLE
element library -> nuclide library

### PR DESCRIPTION
**Pull request by elliottbiondo**
This script adds entries to the ALARA elelib.std file for each nuclide within the file as if it were a pure substance. This allows users to create matlib entries using nuclides of their choosing without having to create custom entries in the elelib.

### CODE REVIEW

**Comment by gonuke** [comment]
What about a short test?  And we might as well put a full nuclib in the repo.

**Comment by elliottbiondo** [comment]
ping @gonuke

**Comment by gonuke** [comment]
nuclib should probably live in the `data` directory instead; see `elelib.std`

**Comment by elliottbiondo** [comment]
Fixed @gonuke.

**Comment by elliottbiondo** [comment]
ping @gonuke

**Comment by gonuke** [comment]
Thanks @elliottbiondo

**Pull request merged**
